// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-c_uCO26Qcpt0ClB3rZ_tzOOixSafud4',
    appId: '1:340331847105:web:c05a5baeed12361c58a340',
    messagingSenderId: '340331847105',
    projectId: 'myproject-d2bf0',
    authDomain: 'myproject-d2bf0.firebaseapp.com',
    storageBucket: 'myproject-d2bf0.appspot.com',
    measurementId: 'G-YM4E35MMCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMKu1zdBzufNC4u38BsUv66wJ4MRxTeds',
    appId: '1:340331847105:android:0deb15d49b38efa258a340',
    messagingSenderId: '340331847105',
    projectId: 'myproject-d2bf0',
    storageBucket: 'myproject-d2bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK-dKxCB697xe17wN9OxQqD4cWORi4xZg',
    appId: '1:340331847105:ios:aff4ec5ebddd384158a340',
    messagingSenderId: '340331847105',
    projectId: 'myproject-d2bf0',
    storageBucket: 'myproject-d2bf0.appspot.com',
    iosBundleId: 'com.example.socialpoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK-dKxCB697xe17wN9OxQqD4cWORi4xZg',
    appId: '1:340331847105:ios:f851f6eaff22d77158a340',
    messagingSenderId: '340331847105',
    projectId: 'myproject-d2bf0',
    storageBucket: 'myproject-d2bf0.appspot.com',
    iosBundleId: 'com.example.socialpoc.RunnerTests',
  );
}
