// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4irrYor_ovsqnX604NkAKoXIHCLgAqx4',
    appId: '1:317704986009:web:0bccf66af1fd79a4e30708',
    messagingSenderId: '317704986009',
    projectId: 'proud-lead-392506',
    authDomain: 'proud-lead-392506.firebaseapp.com',
    storageBucket: 'proud-lead-392506.appspot.com',
    measurementId: 'G-0G28M4RK6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMQJI6OBZIwToDBt8n5inFxDEaOQS3ehM',
    appId: '1:317704986009:android:e0eccb65376cc4d9e30708',
    messagingSenderId: '317704986009',
    projectId: 'proud-lead-392506',
    storageBucket: 'proud-lead-392506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYzlBOpHBwnr9-fE-00H36wVsNYb3vrBI',
    appId: '1:317704986009:ios:e270be77ff2493efe30708',
    messagingSenderId: '317704986009',
    projectId: 'proud-lead-392506',
    storageBucket: 'proud-lead-392506.appspot.com',
    iosBundleId: 'com.example.socialpoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYzlBOpHBwnr9-fE-00H36wVsNYb3vrBI',
    appId: '1:317704986009:ios:4396f4d8cef96610e30708',
    messagingSenderId: '317704986009',
    projectId: 'proud-lead-392506',
    storageBucket: 'proud-lead-392506.appspot.com',
    iosBundleId: 'com.example.socialpoc.RunnerTests',
  );
}
